name: HelloWord
on: workflow_dispatch
jobs:
  build:
    runs-on: ububuntu-latest
    steps:
      - name: build setup
        run: echo "run starting"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test App
        run: echo "test The app"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        run: echo "deploying the app"
      
